#pragma once
#include "order.hpp"
#include "trade.hpp"
#include "price_level.hpp"
#include <map>
#include <unordered_map>
#include <optional>
#include <vector>

namespace lobx {

/// Price-time priority limit order book.
///
/// Bids are stored in a max-map (highest price first).
/// Asks are stored in a min-map (lowest price first).
///
/// `add_limit_order` attempts an immediate match before resting the remainder.
/// Returns a vector of Trades generated by the submission.
class OrderBook {
public:
    /// Add a limit order. Matches against the opposite side immediately.
    /// Remaining qty (if any) rests in the book.
    /// Returns all Trades generated.
    std::vector<Trade> add_limit_order(Order order);

    /// Cancel a resting order by id.
    /// Returns true if found and removed, false otherwise.
    bool cancel(OrderId id);

    // ── Book queries ──────────────────────────────────────────────────────────

    /// Best bid price (highest). Returns nullopt if no bids.
    std::optional<Price> best_bid() const;

    /// Best ask price (lowest). Returns nullopt if no asks.
    std::optional<Price> best_ask() const;

    /// Mid-price in ticks (returns nullopt if one side is empty).
    std::optional<double> mid_price() const;

    /// Spread in ticks (nullopt if either side empty).
    std::optional<Price> spread() const;

    /// Total qty resting on the bid side.
    Quantity total_bid_qty() const;

    /// Total qty resting on the ask side.
    Quantity total_ask_qty() const;

    /// Number of distinct price levels on each side.
    size_t bid_levels() const noexcept { return bids_.size(); }
    size_t ask_levels() const noexcept { return asks_.size(); }

    bool empty() const noexcept { return bids_.empty() && asks_.empty(); }

private:
    // Bids: highest price has priority → reverse (descending) map.
    std::map<Price, PriceLevel, std::greater<Price>> bids_;

    // Asks: lowest price has priority → default (ascending) map.
    std::map<Price, PriceLevel> asks_;

    // Fast lookup: order id → price (for O(log N) cancel).
    std::unordered_map<OrderId, Price> order_index_;

    /// Internal matching loop. Fills `aggressor` against `passive_side`.
    template <typename PassiveMap>
    std::vector<Trade> match(Order& aggressor, PassiveMap& passive_side);

    void rest_order(Order order);
};

} // namespace lobx
